# Numpy
Numerical Python

Numpy is a fundamental package for scientific computing in Python. It provides support for large multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. Numpy is widely used for numerical computations in various domains - data science, machine learning and engineering.

Numpy handles, 1D(vector), 2D, 3D and other high-dimensional arrays.

In [5]:
# installing numpy
!pip install numpy

In [7]:
# importing numpy
import numpy as np

### Creating Arrays
Creating arrays involves using Python's numpy library, which provies a powerful array object called ndarray.

- ### Creating Arrays from Lists
Arrays can be created directly from Python's list using the numpy array() function.

In [13]:
# create 1D array(vector)
arr1 = np.array([20, 25, 65, 75])
arr1

array([20, 25, 65, 75])

In [15]:
# converting list to array
lst = [2, 4, 6, 9]
np.array(lst)

array([2, 4, 6, 9])

In [21]:
# create a 2D array
arr2 = np.array([[2, 4, 6],[3, 5, 9],[8, 11, 10]])
arr2

array([[ 2,  4,  6],
       [ 3,  5,  9],
       [ 8, 11, 10]])

- ### Array Attributes

In [25]:
# Get the shape of the array
arr1.shape

(4,)

In [27]:
arr2.shape

(3, 3)

In [29]:
# get the size of the array (number of elements)
arr1.size

4

In [31]:
arr2.size

9

In [33]:
# get the dimension of the array
arr1.ndim

1

In [35]:
arr2.ndim

2

- ### Creating Arrays Using Built-in Functions

In [39]:
# creating an array filled with zero (0) as element
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
# array filled with one (1) as element
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
# identity matrix - Diagonal numbers are 1 other elements 0
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

- ### Creating Arrays using Random Functions

In [48]:
# create arrarys of floats using random function
# NOTE: number is between 0 and 1
np.random.random(5)

array([0.31405117, 0.98757984, 0.31156205, 0.40576072, 0.34307881])

In [50]:
# rand performs the same fucntion as random but only for 1D array
np.random.rand(5)

array([0.47862888, 0.31955917, 0.86666555, 0.01753239, 0.40413546])

In [54]:
# random can be used for arrays of different dimensions
np.random.random((3, 4))

array([[0.94965697, 0.56941659, 0.46537855, 0.56353067],
       [0.56463923, 0.8753753 , 0.90262379, 0.67473889],
       [0.6872954 , 0.25144191, 0.62622963, 0.05598815]])

In [56]:
# used to generate random integers within a certain range
np.random.randint(1, 10, (3, 3))

array([[3, 6, 5],
       [1, 5, 9],
       [1, 1, 4]])

- ### Seed Reproducibility
It is used to replicate a random number. Hence, setting the same seed value ensures identical output.

In [61]:
np.random.seed(25)
np.random.randint(1, 100, (4, 5))

array([[ 5, 63, 91, 16, 62],
       [24, 45, 51,  9, 29],
       [ 5, 90, 32, 70,  2],
       [40,  4, 89, 56,  4]])

- ### Basic Array Operations

In [64]:
arr1

array([20, 25, 65, 75])

In [66]:
# Adding to an array - Broadscating
# Adds to each element in the array
arr1 + 20

array([40, 45, 85, 95])

In [68]:
arr3 = np.array([12, 14, 16, 28])

In [70]:
arr1 + arr3

array([ 32,  39,  81, 103])

In [72]:
# multiplication of arrays
arr1 * arr3

array([ 240,  350, 1040, 2100])

In [74]:
arr4 = np.array([[1, 2, 3, 4], [10, 11, 12, 13], [0.2, 1.1, 1.8, 2.6]])
arr4

array([[ 1. ,  2. ,  3. ,  4. ],
       [10. , 11. , 12. , 13. ],
       [ 0.2,  1.1,  1.8,  2.6]])

In [76]:
row = [3, 4, 6, 8]

In [78]:
arr4 + row

array([[ 4. ,  6. ,  9. , 12. ],
       [13. , 15. , 18. , 21. ],
       [ 3.2,  5.1,  7.8, 10.6]])

- ### Array Indexing and Slicing
Array indexing and slicing in NumPy are powerful tools for accessing and manipulating subsets of data in arrays.

In [84]:
arr1

array([20, 25, 65, 75])

In [86]:
# indexing
arr1[2]

65

In [88]:
# slicing in array
arr1[1:3]

array([25, 65])

In [96]:
arr4

array([[ 1. ,  2. ,  3. ,  4. ],
       [10. , 11. , 12. , 13. ],
       [ 0.2,  1.1,  1.8,  2.6]])

In [100]:
# Getting the first row and all the columns
arr4[0, :]

array([1., 2., 3., 4.])

In [102]:
# Getting first and second row with all the columns
arr4[0:2, :]

array([[ 1.,  2.,  3.,  4.],
       [10., 11., 12., 13.]])

- ### Modifying
This involves changing elements in a array.

In [106]:
arr1

array([20, 25, 65, 75])

In [110]:
arr1[1] = 60
arr1

array([20, 60, 65, 75])

- ### Array Manipulation
Array manipulation in NumPy refers to modifying arrays to fit desired shapes, sizes, or structures. This includes operations like reshaping, flattening, transposing, and concatenating arrays, among others.

- ##### Reshaping
Reshaping involves changing the shape (dimensions) of an array without altering its data. The total number of elements must remain the same.

In [122]:
aray = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
# reshaping
reshp_aray = aray.reshape(2, 5)
reshp_aray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

- ##### Transposing
Transposing flips an array's axes. For example, rows become columns, and vice versa. This is especially useful for matrix operations and reshaping multi-dimensional data.

In [129]:
# transposing
reshp_aray.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

- ##### Flattening
Flattening reduces a multi-dimensional array to a 1D array. This operation is commonly used when you need to perform operations that require a single sequence of elements.

In [132]:
# flattening
reshp_aray.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- ##### Splitting
Array Splitting in NumPy refers to dividing an array into multiple subarrays. This is useful when you need to process or analyze parts of an array independently.

Splitting Methods in NumPy
- `np.split`: General-purpose splitting based on specified indices.
- `np.array_split`: Allows uneven splitting.
- `np.hsplit`: Splits along columns (horizontal split for 2D arrays).
- `np.vsplit`: Splits along rows (vertical split for 2D arrays).
- `np.dsplit`: Splits along the depth (third axis) for 3D arrays.

In [136]:
# general spliting
np.split(aray, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

- ##### Concatenating
In NumPy, concatenation refers to joining two or more arrays along a specified axis. The arrays must have compatible shapes along the axis being concatenated.

In [139]:
ary = np.array([2, 4, 6, 7])
ary

array([2, 4, 6, 7])

In [141]:
rya = np.array([3, 5, 8, 9])
rya

array([3, 5, 8, 9])

In [143]:
# concatenating
np.concatenate((ary, rya))

array([2, 4, 6, 7, 3, 5, 8, 9])

- ### Mathematical Operations

In [146]:
# find the square root of an array
ary

array([2, 4, 6, 7])

In [148]:
np.sqrt(ary)

array([1.41421356, 2.        , 2.44948974, 2.64575131])

In [150]:
# sum of an array
ary.sum()

19